#!/bin/bash
# smartsharp.pl
#  https://github.com/jbylund/imagemagick
#  goal is to sharpen images better than '-shapen 0x1' and similar.
#  could be improved by smarpening the value channel alone, and leaving color alone
#  sharpening color really only increases noise
#  and most of what we percieve as sharpness is in the value channel anyways

# initial stuff
echo "Called with '$1'"
#  - normalize to basename (clip path)
basename=`basename "$1"`
echo " - basename     = '${basename}'"
#  - grab the extension
extension=`echo "${basename}" | sed 's/^.*\.//'`
echo " - extension    = '${extension}'"
#  - snip the extension
basename=`echo "${basename}" | sed 's/\..*$//'`
echo " - new basename = '${basename}'"

# create a working directory. to do this, we first determine mktemp version:
#  - if we're on linux, --directory exists.
#  - if we're on OSX, -d exists
echo -n "Generating tempdir... "
template="tmp-${basename}"
linux=0
`mktemp --help 2>&1 |grep directory` && tmpdir=`mktemp --directory "${template}"` || tmpdir=`mktemp -d "${template}"`
echo "'${tmpdir}'"

# perform actual sharpening
echo "Performing sharpen... "
#  - generate blurred mask and inverse mask
echo -n " - Step 1... "
convert "${1}" -blur 0x3 -define convolve:scale='-1!' -morphology Convolve Laplacian:0 -colorspace Gray -contrast-stretch 4% -blur 0x5 -contrast-stretch 4% -write "${tmpdir}/mask.ppm" -negate "${tmpdir}/inverse_mask.ppm" && echo "ok"
echo -n " - Step 2... "
convert "${1}" -blur 0x2 -write "${tmpdir}/blurred.ppm" -compose Multiply "${tmpdir}/inverse_mask.ppm" -composite "${tmpdir}/product.ppm" && echo "ok"
echo -n " - Step 3... "
convert "${1}" -unsharp 9x2.5+1+0.0 -write "${tmpdir}/sharp.ppm" -compose Multiply "${tmpdir}/mask.ppm" -composite "${tmpdir}/product_sharp.ppm" && echo "ok"
echo -n " - Step 4... "
convert "${tmpdir}/sharp.ppm" "${tmpdir}/blurred.ppm" "${tmpdir}/inverse_mask.ppm" -composite "${basename}_sharp.${extension}" && echo "ok"

# clean up tmpdir
echo -n "Cleaning up... "
rm "${tmpdir}/{sharp,blurred,inverse_mask,product,mask,product_sharp}.ppm" && echo "ok"
exit 0
